### ISSUE TITLE
listItemIndent value of "1" is still replaced by tabs.

### ISSUE THREAD

**Issue by stcbus** [mrmlnc/vscode-remark#15]
Hello, I read the documentation and have set the remark.format rules `listItemIndent` option to "1" in my settings.json. When I tell VSCode to do the remark formatting, it is still adding the 3 spaces instead. My other options (like setext: true) are correctly followed.

Relevant portion:

```
"remark.format": {
        "rules": {
            "setext": true,
            "listItemIndent ": "1",
            "rule": "*"
        }
    },
```

**Comment by Stanzilla** [comment]
Same here, any advice @mrmlnc?

**Comment by sagebind** [comment]
Found the problem, `listItemIndent` is indeed respected, but when you use IntelliSense to create the setting it adds an extra space at the end of the JSON key, making Remark not recognize it.

I created #19 to fix that. In the meantime, just delete the extra space in your config.
