### ISSUE TITLE
Implement remark-lint

### ISSUE THREAD

**Issue by TimonVS** [mrmlnc/vscode-remark#4]
Do you have plans to integrate [remark-lint](https://github.com/wooorm/remark-lint)?

If you need any help, I'd be glad to give a helping hand.

**Comment by mrmlnc** [comment]
Hello, @TimonVS,

Yes, I'm going to make this plugin, but separately (because for linters I should use VS Code Language Server).

My personal queue of plugins that I'm going to create: https://github.com/mrmlnc/vscode-extensions-queue. Right now I'm working on autocompletion for Less.

**Comment by TimonVS** [comment]
Cool! Let me know if I can help.

**Comment by wooorm** [comment]
@remarkjs you mean? 😉

How can I help?

**Comment by mrmlnc** [comment]
Hi,

Unfortunately, now I don't have time to write new plugins and have a little time to support old ones. If you can do it on your own, then I am ready to help you in any way.

**Comment by mrmlnc** [comment]
Already covered by https://github.com/drewbourne/vscode-remark-lint.
