### ISSUE TITLE
Markdown Preview window, rendered by remark-html

### ISSUE THREAD

**Issue by Rokt33r** [mrmlnc/vscode-remark#6]
VS code supports markdown preview. Is it possible to replace the renderer of the preview with Remark html?

**Comment by mrmlnc** [comment]
Hello, @Rokt33r,

IMO, no, because i don't see any API for try to update renderer of the preview. We can create your custom Markdown preview, but your will lose more features (from current implementation of Markdown preview).

**Comment by Rokt33r** [comment]
Okay, I'll consider to make a new preview plugin. Losing some features(auto scrolling?) is quite minor problem for me. 
Thanks for the fast reply. 😃 😃 😃

**Comment by mrmlnc** [comment]
If you have free time, you can send PR ❤️

**Comment by Rokt33r** [comment]
I'll do gladly. 👍
